/**
 * types.ts — Shared TypeScript interfaces for the FlowState pipeline.
 * Used by both producer, consumer, and WebSocket server.
 */

/** Raw transaction payload generated by the producer and published to Kafka. */
export interface Transaction {
  /** UUID v4 — uniquely identifies this transaction across the system */
  transactionId: string;
  /** Pool of 20 synthetic user IDs, e.g., "user_001" */
  userId: string;
  /** Transaction amount in USD (0.00 – 5000.00) */
  amount: number;
  /** ISO 8601 timestamp of when the transaction was generated */
  timestamp: string;
  /** Human-readable city/country string, e.g., "New York, US" */
  location: string;
}

/** Enriched transaction produced by the consumer after fraud analysis. */
export interface ProcessedTransaction extends Transaction {
  /**
   * Composite risk score (0–100).
   *   - 0–50: proportional to transaction amount (max $5000 = 50 pts)
   *   - 0–50: proportional to velocity in last 60s (10+ tx = 50 pts)
   */
  riskScore: number;
  /** true if riskScore > FRAUD_THRESHOLD (default: 75) */
  isFraud: boolean;
  /** Number of transactions this userId made in the last 60s (Redis fixed window) */
  velocity: number;
}
